###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "pen",
  "price": 2.99 
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "pencil",
  "price": 1.99 
}